//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeAds.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbAdvirtiser
    {
        public int ID { get; set; }
        public int Number_Of_Offered_Products { get; set; }
        public string SellerAddress { get; set; }
    }
}
