//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeAds.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbLocation
    {
        public int LocationId { get; set; }
        public string CountryName { get; set; }
        public string GovernorateName { get; set; }
        public string CityName { get; set; }
        public string LocationDetails { get; set; }
    }
}
