//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeAds.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbProduct
    {
        public int ProductID { get; set; }
        public int CategoryId { get; set; }
        public string ProductName { get; set; }
        public decimal ProductPrice { get; set; }
        public string ProductImages { get; set; }
        public string ProductDescription { get; set; }
        public string Number_Of_Items { get; set; }
        public int ProductSellerID { get; set; }
        public System.DateTime AdvirtisementDate { get; set; }
    }
}
