//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeAds.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbUser
    {
        public int ID_Number { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserEmail { get; set; }
        public string UserGender { get; set; }
        public string UserProfileImage { get; set; }
        public int UserPhoneNumber { get; set; }
    }
}
